[build]
  command = "npm run build && npm run db:generate"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# API proxy
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 