/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SmartWalletImplementation,
  SmartWalletImplementationInterface,
} from "../../../contracts/SmartWalletFactory.sol/SmartWalletImplementation";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "isValidSignature",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610030576001808060a01b0319818160005416176000558154161760015561024890816100368239f35b600080fdfe608060408181526004908136101561001657600080fd5b600092833560e01c9081631626ba7e14610178575080638da5cb5b14610150578063c45a0155146101235763c4d66de81461005057600080fd5b3461011f57602036600319011261011f576001600160a01b0382358181169391929084900361011b578454928084166100e25760015416330361009f5750506001600160a01b03191617815580f35b906020606492519162461bcd60e51b8352820152601b60248201527f4f6e6c7920666163746f72792063616e20696e697469616c697a6500000000006044820152fd5b815162461bcd60e51b81526020818501526013602482015272105b1c9958591e481a5b9a5d1a585b1a5e9959606a1b6044820152606490fd5b8480fd5b8280fd5b83823461014c578160031936011261014c5760015490516001600160a01b039091168152602090f35b5080fd5b83823461014c578160031936011261014c57905490516001600160a01b039091168152602090f35b849291503461011f578160031936011261011f5760243567ffffffffffffffff80821161011b573660238301121561011b5781860135958187116101ff57601f8701601f19908116603f01168401918211848310176101ff5750835284825236602486830101116101fb5784849260209660248894018483013701015251908152f35b8380fd5b634e487b7160e01b865260419052602485fdfea264697066735822122007587ae287ab2ce67a510c8f401ced7d7106ba252bf1f043419626f49d04d86964736f6c63430008140033";

type SmartWalletImplementationConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SmartWalletImplementationConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SmartWalletImplementation__factory extends ContractFactory {
  constructor(...args: SmartWalletImplementationConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<SmartWalletImplementation> {
    return super.deploy(overrides || {}) as Promise<SmartWalletImplementation>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SmartWalletImplementation {
    return super.attach(address) as SmartWalletImplementation;
  }
  override connect(signer: Signer): SmartWalletImplementation__factory {
    return super.connect(signer) as SmartWalletImplementation__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SmartWalletImplementationInterface {
    return new utils.Interface(_abi) as SmartWalletImplementationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SmartWalletImplementation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SmartWalletImplementation;
  }
}
