/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SmartWalletImplementation,
  SmartWalletImplementationInterface,
} from "../../contracts/SmartWalletImplementation";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "isValidSignature",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461002d5760018060a01b031980600054166000556001541660015561020c90816100338239f35b600080fdfe6080604081815260048036101561001557600080fd5b600092833560e01c9081631626ba7e1461013c575080638da5cb5b14610114578063c45a0155146100e75763c4d66de81461004f57600080fd5b346100e35760203660031901126100e3576001600160a01b039181358381169291908390036100df5784549384166100a65750506bffffffffffffffffffffffff60a01b8092161782553390600154161760015580f35b906020606492519162461bcd60e51b83528201526013602482015272105b1c9958591e481a5b9a5d1a585b1a5e9959606a1b6044820152fd5b8480fd5b8280fd5b50503461011057816003193601126101105760015490516001600160a01b039091168152602090f35b5080fd5b505034610110578160031936011261011057905490516001600160a01b039091168152602090f35b84848492346100e357816003193601126100e35760243567ffffffffffffffff8082116100df57366023830112156100df5781860135958187116101c357601f8701601f19908116603f01168401918211848310176101c35750835284825236602486830101116101bf5784849260209660248894018483013701015251908152f35b8380fd5b634e487b7160e01b865260419052602485fdfea2646970667358221220c1c4d898cc152f5a858b063f735ea6fe900ecf009db14717f8120b722fcf72de64736f6c63430008140033";

type SmartWalletImplementationConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SmartWalletImplementationConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SmartWalletImplementation__factory extends ContractFactory {
  constructor(...args: SmartWalletImplementationConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<SmartWalletImplementation> {
    return super.deploy(overrides || {}) as Promise<SmartWalletImplementation>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SmartWalletImplementation {
    return super.attach(address) as SmartWalletImplementation;
  }
  override connect(signer: Signer): SmartWalletImplementation__factory {
    return super.connect(signer) as SmartWalletImplementation__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SmartWalletImplementationInterface {
    return new utils.Interface(_abi) as SmartWalletImplementationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SmartWalletImplementation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SmartWalletImplementation;
  }
}
